name: Sync Fork

on:
  schedule:
    # 每天 UTC 时间凌晨 1 点自动执行同步
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure git
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'

    - name: Sync with upstream
      run: |
        git remote add upstream https://github.com/teralomaniac/clewd.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push origin master
